RegieMag/Controllers/ProductsController.cs
using Microsoft.AspNet.Identity;
using PagedList;
using RegieMag.Models;
using RegieMag.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;


namespace RegieMag.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        public ActionResult Index(string category, string search, string sortBy, int? page)
        {
            //instantiate a new view model
            ProductIndexViewModel viewModel = new ProductIndexViewModel();

            var products = db.Products.Include(p => p.Category).Include(p => p.Owner);
            if (!String.IsNullOrEmpty(search))
            {
                products = products.Where(p => p.Name.Contains(search) ||
                p.Description.Contains(search) ||
                p.Category.Name.Contains(search));
                viewModel.Search = search;
            }
            //group search results into categories and count how many items in each category
            viewModel.CatsWithCount = from matchingProducts in products
                                      where
                                      matchingProducts.CategoryID != null
                                      group matchingProducts by
                                      matchingProducts.Category.Name into
                                      catGroup
                                      select new CategoryWithCount()
                                      {
                                          CategoryName = catGroup.Key,
                                          ProductCount = catGroup.Count()
                                      };
            if (!String.IsNullOrEmpty(category))
            {
                products = products.Where(p => p.Category.Name == category);
                viewModel.Category = category;
            }
            //sort the results
            switch (sortBy)
            {
                case "price_lowest":
                    products = products.OrderBy(p => p.Price);
                    break;
                case "price_highest":
                    products = products.OrderByDescending(p => p.Price);
                    break;
                default:
                    products = products.OrderBy(p => p.Name);
                    break;
            }
            int currentPage = (page ?? 1);
            viewModel.Products = products.ToPagedList(currentPage, Constants.PageItems);
            viewModel.SortBy = sortBy;
            viewModel.Sorts = new Dictionary<string, string>
            {
                {"Crescator dupa pret", "price_lowest" },
                {"Descrescator dupa pret", "price_highest" }
            };
            return View(viewModel);

        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ProductViewModel viewModel = new ProductViewModel();
            viewModel.CategoryList = new SelectList(db.Categories, "ID", "Name");
            viewModel.ImageLists = new List<SelectList>();
            for (int i = 0; i < Constants.NumberOfProductImages; i++)
            {
                viewModel.ImageLists.Add(new SelectList(db.ProductImages, "ID", "FileName"));
            }
            return View(viewModel);
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel viewModel)
        {
            var userId = User.Identity.GetUserId();

            Product product = new Product();
            product.Name = viewModel.Name;
            product.Description = viewModel.Description;
            product.Price = viewModel.Price;
            product.CategoryID = viewModel.CategoryID;
            product.OwnerID = userId; 
            //get a list of selected images without any blanks
            string[] productImages = viewModel.ProductImages.Where(pi =>
            !string.IsNullOrEmpty(pi)).ToArray();

            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            viewModel.CategoryList = new SelectList(db.Categories, "ID", "Name", product.CategoryID);
            viewModel.ImageLists = new List<SelectList>();
            for (int i = 0; i < Constants.NumberOfProductImages; i++)
            {
                viewModel.ImageLists.Add(new SelectList(db.ProductImages, "ID", "FileName",
                viewModel.ProductImages[i]));
            }
            return View(viewModel);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            ProductViewModel viewModel = new ProductViewModel();
            viewModel.CategoryList = new SelectList(db.Categories, "ID", "Name", product.CategoryID);
            viewModel.ImageLists = new List<SelectList>();

            for (int i = viewModel.ImageLists.Count; i < Constants.NumberOfProductImages; i++)
            {
                viewModel.ImageLists.Add(new SelectList(db.ProductImages, "ID", "FileName"));
            }
            viewModel.ID = product.ID;
            viewModel.Name = product.Name;
            viewModel.Description = product.Description;
            viewModel.Price = product.Price;
            return View(viewModel);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductViewModel viewModel)
        {
            var productToUpdate = db.Products.Where(p => p.ID==viewModel.ID).Single();
            if (TryUpdateModel(productToUpdate, "", new string[] { "Name", "Description", "Price","CategoryID" }))
            {
                //get a list of selected images without any blanks
                string[] productImages = viewModel.ProductImages.Where(pi =>!string.IsNullOrEmpty(pi)).ToArray();

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var product = db.Products.Include(p => p.Category).Single(p => p.ID == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index", "Categories", null);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RegieMag/Views/Shared/_CreateRegisterUserPartial.cshtml
@model RegieMag.Models.RegisterViewModel
<hr />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-group">
    @Html.LabelFor(model => model.Email, htmlAttributes: new{ @class = "control-label col-md-2"})
    <div class="col-md-10">
        @Html.EditorFor(model => model.Email, new{ htmlAttributes = new{ @class = "form-control" }})
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Password, htmlAttributes: new{ @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Password, new { htmlAttributes = new{ @class = "form-control"}})
        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new{ @class = "control-label col-md-2"})
    <div class="col-md-10">
        @Html.EditorFor(model => model.ConfirmPassword, new{ htmlAttributes = new{ @class ="form-control"}})
        @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new{ @class = "text-danger"})
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.FirstName, htmlAttributes: new{ @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new{ @class = "form-control"}})
        @Html.ValidationMessageFor(model => model.FirstName, "", new{ @class = "text-danger"})
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.LastName, htmlAttributes: new{ @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.LastName, new{ htmlAttributes = new{ @class = "form-control"}})
        @Html.ValidationMessageFor(model => model.LastName, "", new{ @class = "text-danger"})
    </div>
</div>

RegieMag/Views/Shared/_EditUserPartial.cshtml
@model RegieMag.Models.EditUserViewModel

<hr />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-group">
    @Html.LabelFor(model => model.Email, htmlAttributes: new{ @class = "control-label col-md-2"})
    <div class="col-md-10">
        @Html.EditorFor(model => model.Email, new{ htmlAttributes = new{ @class = "form-control", @readonly = "readonly" }})
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.FirstName, htmlAttributes: new{ @class = "control-label col-md-2"})
    <div class="col-md-10">
        @Html.EditorFor(model => model.FirstName, new{ htmlAttributes = new{ @class = "form-control" }})
        @Html.ValidationMessageFor(model => model.FirstName, "", new{ @class = "text-danger"})
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.LastName, htmlAttributes: new{ @class = "control-label col-md-2"})
    <div class="col-md-10">
        @Html.EditorFor(model => model.LastName, new{ htmlAttributes = new{ @class = "form-control"}})
        @Html.ValidationMessageFor(model => model.LastName, "", new{ @class = "text-danger"})
    </div>
</div>

RegieMag/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("RegieMag", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>

        
                <div class="navbar-collapse collapse">
            @if (User.IsInRole("Admin") || User.IsInRole("User"))
            {
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Produsele mele", "Index", "Categories")</li>
                    <li>@Html.ActionLink("Cumpara", "Index", "Products")</li>
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                    }
                </ul>

                using (Html.BeginForm("Index", "Products", FormMethod.Get, new { @class = "navbar-form navbar-left" }))
                {
                    <div class="form-group">
                        @Html.TextBox("Search", null, new { @class = "form-control", @placeholder = "Cauta produse..." })
                    </div>
                    <button type="submit" class="btn btn-default">Cauta</button>
                }
            }
            @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - RegieMAG</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>

RegieMag/Views/Shared/_ProductEditCreatePartial.cshtml
@model RegieMag.ViewModels.ProductViewModel

<div class="form-group">
    <label class = "control-label col-md-2">Nume</label>
    <div class="col-md-10">
        @Html.EditorFor(model => model.Name, new{ htmlAttributes = new {  @class = "form-control"}})
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-2">Descriere</label>
    <div class="col-md-10">
        @Html.EditorFor(model => model.Description, new{ htmlAttributes = new { @class ="form-control"}})
        @Html.ValidationMessageFor(model => model.Description, "", new{ @class = "text-danger"})
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-2">Pret</label>
    <div class="col-md-10">
        @Html.EditorFor(model => model.Price, new{ htmlAttributes = new{@class = "form-control" }})
        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-2">Categorie</label>
    <div class="col-md-10">
        @Html.DropDownListFor(vm => vm.CategoryID, Model.CategoryList, htmlAttributes: new { @class = "form-control"})
        @Html.ValidationMessageFor(model => model.CategoryID, "", new{ @class = "text-danger"})
    </div>
</div>

<div class="form-group">
    <label class="control-label col-md-2">Imaginea @(1):</label>
    <div class="col-md-10">
        @Html.DropDownListFor(vm => vm.ProductImages, Model.ImageLists[0], "Alege o imagine",htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ImageLists, "", new{@class = "text-danger"})
    </div>
</div>

RegieMag/Views/Shared/_UserDetailsPartial.cshtml
@model RegieMag.Models.ApplicationUser
<dt>
    @Html.DisplayNameFor(model => model.FirstName)
</dt>
<dd>
    @Html.DisplayFor(model => model.FirstName)
</dd>
<dt>
    @Html.DisplayNameFor(model => model.LastName)
</dt>
<dd>
    @Html.DisplayFor(model => model.LastName)
</dd>
<dt>
    @Html.DisplayNameFor(model => model.Email)
</dt>
<dd>
    @Html.DisplayFor(model => model.Email)
</dd>